---
- include: create_networks.yml

- name: Create the instance
  ec2:
    region: "{{ ec2stack_region }}"
    image: "{{
      ec2stack_images[ec2stack_region][ec2stack_config.image]
      | default(ec2stack_config.image)
    }}"
    instance_type: "{{ ec2stack_config.instance_type }}"
    vpc_subnet_id: "{{ subnets | map(attribute='id') | shuffle | first }}"
    assign_public_ip: "{{ ec2stack_config.assign_public_ip | default('yes') }}"
    instance_profile_name: "{{ ec2stack_config.instance_profile_name | default() }}"
    groups: "{{ ec2stack_config.groups }}"
    instance_tags:
      Name: "{{ ec2stack_config.name }}"
    key_name: "{{ ec2stack_config.key_name }}"
    exact_count: 1
    count_tag: Name
  register: result

- set_fact: ec2_instance="{{ result.tagged_instances[0] }}"

- name: Create states directory
  file:
    path: "{{ ec2stack_states_path }}"
    state: directory

- name: Save the instance state
  template:
    src: state.yml.j2
    dest: "{{ ec2stack_states_path }}/{{ ec2stack_config.name }}.yml"
