---
- name: Terminate the instance
  ec2:
    region: "{{ ec2stack_region }}"
    instance_id: "{{ ec2stack_state.instance_id }}"
    state: absent

- name: Delete the instance state
  file:
    path: "{{ ec2stack_states_path }}/{{ ec2stack_name }}.yml"
    state: absent
